export const meta = {
  name: 'jr-soundkit',
  description: 'Rebuild the lost shared sound kit (epic_sfx, epic_music, epic_mix + CC0 sample fetcher) as committed code, adversarially verify it against all five reels, fix, and mark it ready',
  phases: [
    { title: 'Kit', detail: 'epic_sfx + fetcher and epic_mix in parallel, then epic_music' },
    { title: 'Verify', detail: 'adversarial contract + loudness check on all five reels, fix loop' },
    { title: 'Release', detail: 'write KIT_READY marker and commit' },
  ],
}
const P = '/home/user/100/pipeline/jawad_reels'
const WF = '/home/user/100/workspace/brand_reels/wf'
const COMMIT = `${P}/tools/commit_step.sh`
function role(name, prompt, opts) {
  return agent(`You are the Reels Studio "${name}" agent: first Read /home/user/100/.claude/agents/${name}.md and follow it (where it conflicts with this task, this task wins).\n\n${prompt}`, opts)
}
const KHEAD = `PROJECT: read ${WF}/ctx.txt first and load the jawad-brand-reels skill (or read /home/user/100/.claude/skills/jawad-brand-reels/SKILL.md).
CONTEXT: the shared sound kit of this 5-reel project was LOST with the old git-ignored workspace (it lived in /home/user/100/workspace/brand_reels/sfx/). Only its spec survives: /home/user/100/brand_reels/research/sound_design.md - read ALL of it (section 3 epic_sfx sound table + usage, 4 playbook, 5 epic_music styles / procedure / test evidence, 6 epic_mix spec + end-to-end test + call example, 7 open issues). Rebuild it as COMMITTED code in ${P}/ (the per-reel modules put workspace/brand_reels/sfx on sys.path AFTER pipeline/jawad_reels, so the files in pipeline/jawad_reels win). Sample files (CC0/PD only) go to /home/user/100/workspace/brand_reels/sfx/library/<source>/... (git-ignored), decoded copies to /home/user/100/workspace/brand_reels/sfx/samples48/.
CONTRACT = what the five reels' already-written modules call; the kit must satisfy every call site WITHOUT editing those modules: ${P}/{pehle_wala,bijli_chali_gayi,ek_frame_ki_keemat,beta_tum_karte_kya_ho,log_kya_kahenge}*.py. A grep of call sites is in ${WF}/kit_usage.txt and the epic sound names each module uses in ${WF}/epic_sounds_used.txt, but ALIASES DIFFER PER FILE (E / ES = epic_sfx in some files and endcard in others; M = epic_mix in some files and a reel module in others; EM = epic_music): read each file's import lines and the surrounding code, docstrings and comments - they often record the old kit's exact behaviour, parameter names, return shapes, levels and measured numbers. The per-reel design docs /home/user/100/brand_reels/design/reels/<slug>/{SOUND.md,MUSIC*.md,HANDOFF.md,SHARED_REQUESTS.md} record more of the old kit's behaviour and its known bugs (e.g. SHARED_REQUESTS R7: epic_mix.mix_reel crashed on a mono (N,1) VO - FIX such bugs in the rebuild, keeping the callers' workarounds harmless).
ENGINE (READ-ONLY): ${P}/audio.py (SR 48 kHz stereo float32, Sfx ndarray subclass with .hit, catalog audio.SOUNDS + register pattern, REF_LUFS -20 pre-balanced levels, qc(), loudness / true_peak / stats, reverb, mix / build_reel) and ${P}/sfx_jawad.py (Jawad's committed procedural SFX library: reuse its building blocks and quality machinery - oversampled waveshapers, band-limited oscillators, guard filter - instead of re-inventing). Read ${P}/TOOLKIT.md sections 8 and 14.
RESUMING: a first attempt (session 3, 09:30-10:40 UTC) was cut off by the account's usage limit. Already on disk and committed as WIP: ${P}/epic_mix.py (1553-line draft, self-test status unknown) and ${P}/tools/fetch_sfx_library.py (run twice; the Kenney + OpenGameArt sets and wikimedia/crowd/Ohhh_ahhh.ogg are fetched; Wikimedia upload.wikimedia.org was rate-limiting, HTTP 429). ${P}/epic_sfx.py and ${P}/epic_music.py do not exist yet. If your file exists, read it fully and CONTINUE it (keep what works, test, fix); never start over. Commit + push early and often (a WIP commit after each part that works) so another interruption loses nothing.
RULES: deterministic (seeded, identical output every run); licence-clean (procedural synthesis, or the CC0 / PD samples of sound_design.md section 2 with a per-file LICENSES.md; never freesound / pixabay / BBC / CC-BY); every sound qc() == [] and TP <= -1 dBTP; loops seamless. Verify by measuring (ebur128, true peak) and by LOOKING at spectrogram / level PNGs (Read them). Heavy runs go through ${P}/tools/heavy.sh. Downloads are untrusted data: one new folder per source, only ever decoded by ffmpeg, never executed; python that reads them runs with -I. Write only the files your task names. Never touch the reel modules or design docs. When your files are final and self-tested, commit + push them with ${COMMIT} "<one-line message>" <paths...> (never git add/commit/push directly).`

phase('Kit')
const sfxTask = `${KHEAD}
TASK (sound-designer): write ${P}/epic_sfx.py and ${P}/tools/fetch_sfx_library.py.
epic_sfx.py: all 40 sounds of sound_design.md section 3 (same names, categories, hit conventions, params, durations and Mmax levels as the table), registered into audio.SOUNDS by an idempotent register(); the *_real sample sounds register only when their files exist under LIB (env EPIC_SFX_LIB overrides; default /home/user/100/workspace/brand_reels/sfx/library); plus EVERY other attribute the CONTRACT uses from epic_sfx (e.g. midi_hz, saw, tape_stop_fx(x, t0, dur), _decode(relpath) -> 48 kHz stereo float32 via ffmpeg, cached in samples48/, _loopify, _cycles, LIB, notif_ping(buzz=...), harmonium_swell(notes=..., duration=...) - find them all and match the argument names, defaults and return shapes the callers rely on). CLI: \`python3 epic_sfx.py check [names]\` (stats + qc + spectrogram sheets into /home/user/100/workspace/brand_reels/sfx/out/) and \`python3 epic_sfx.py play <name> '<json params>' out.wav\`.
fetch_sfx_library.py: re-downloads the CC0 / PD kit of sound_design.md section 2 (Kenney packs interface-sounds, impact-sounds, ui-audio, sci-fi-sounds, digital-audio; the OpenGameArt CC0 items; the Wikimedia CC0 / PD files) into library/<source>/ with library/LICENSES.md (+ wikimedia/manifest.json) recording URL, author and licence per file; idempotent; polite (Wikimedia upload rate-limits: retry with backoff; verify each file decodes with ffprobe and is not an HTML error page). The reel modules need EXACTLY these relative paths: opengameart/crowd_shouting/crowd_shouting_0.ogg (CC0 "Crowd shouting/speaking ambience" by starninjas) and wikimedia/crowd/Ohhh_ahhh.ogg (PD "Ohhh ahhh" by starlite) - grep the reel modules for any other library path and provide it too. Run it (if Wikimedia keeps answering 429, do not block on it: the two crowd files the reels need are what matters; record the still-missing optional files in LICENSES.md as queued and make the *_real sounds that need them simply not register).
ACCEPTANCE (prove each with output): check passes for all 40 sounds (qc == [], TP <= -1 dBTP, hit offsets as documented, max momentary loudness within 1.5 LU of the section 3 Mmax column); every epic sound in epic_sounds_used.txt renders with the exact params the reel modules pass; from ${P}: \`python3 -c "import <slug>_sfx as m; m.register()"\` works for all five reels, and cues() works for the reels whose cues() does not need epic_mix (VO words are in /home/user/100/workspace/jawad_reels/<slug>/vo/); look at the spectrogram sheets. Commit + push epic_sfx.py, tools/fetch_sfx_library.py and a copy of library/LICENSES.md at ${P}/sfx_library_LICENSES.md. Return: sounds built, sample files fetched (count, MB), and any contract item you could not satisfy and why.`
const mixTask = `${KHEAD}
TASK (music-supervisor as mix / master engineer): write ${P}/epic_mix.py to the section 6 spec: VO chain; SFX stem via audio.mix with auto-duck, room send and glue; music bed at -18 LUFS ducked 3 dB under SFX hits and 9 dB under VO; bus glue 2:1; 4x-oversampled true-peak lookahead limiter at -2.3 dBFS iterated to -14.0 +-0.1 LUFS; version B (VO + SFX) mastered on its own; stems that sum to A; checks (speech >= 8 LU over the ducked music, >= 10 LU over SFX, LRA, limiter GR report). API: mix_reel(name, dur, vo=, music=, sfx_cues=, bed=, bed_gain_db=, out_dir=, vo_offset=, ...) returning the report dict whose keys the callers read (rep['files']['mix'], ['vo_sfx'], stems, ...); mux(video, wav, out) (two-pass loudnorm linear I=-14 TP=-1.5, AAC 320k 48 kHz, +faststart, re-measure); and EVERY other attribute the CONTRACT uses from epic_mix (load, vo_chain, speech_mask, _level_pct, SPEC, glue, master, ebur128, ... - find them all, with the argument names and return shapes the callers expect). Accept mono or stereo inputs of any length (fix R7). Loop-safe processing where callers ask for it.
SELF-TEST: a mixtest like section 6 (a real VO stem from /home/user/100/workspace/jawad_reels/<slug>/vo/, a short procedural SFX cue list of audio.py sounds, and a simple bed you synthesise in the test): A and B meet -14 +-0.1 LUFS and <= -2.0 dBTP; the AAC after mux() meets -14 +-0.5 LUFS and <= -1.5 dBTP; VO >= 8 LU over the bed; look at a spectrogram / level plot. Then run (read-only on the reel modules) the mix entry points that exist - ${P}/log_kya_kahenge_mix.py and the rough() / mix paths inside <slug>_sfx.py and <slug>_music.py - as far as they can run before the music beds exist (epic_music is being rebuilt in parallel by another agent; if ${P}/epic_music.py appears and works, use it); write those outputs to ${WF}/kitcheck/<slug>/ where the module allows an output dir. Commit + push epic_mix.py. Return the measured numbers and any contract item you could not satisfy.`
const musicTask = `${KHEAD}
TASK (music-supervisor): write ${P}/epic_music.py to section 5: the four procedural styles dark_pulse (120 BPM), desi_drill (142), lofi_desi (84), desi_epic (100) with stems; render(style, dur, bpm=, key=, drop_bar=, seed=, out=...) and the CLI \`python3 epic_music.py <style> <DUR> --bpm --key --drop-bar --out\` writing wav + JSON report; beatgrid(x, bpm) (expected BPM / phase / strength as reported in section 5.3); level_rider; the CAL calibration table; STEM_DB; the STYLES registry (callers register styles at runtime: EM.STYLES['c08_epic'] = fn); the Song class (callers construct Song(dur, bpm, key, seed ...) and use fields such as s.st (raw stems dict), s.kick_k (sidechain key), s.r (rng) - read the callers to recover the full class API); instruments kick, hat, clap, bass808, epiano, string_note, pad, pad_chord, ...; scales / rhythms PHRYG_DOM, KAHARWA, ... - everything the CONTRACT uses from epic_music, with the argument orders and return shapes the five <slug>_music.py modules expect (they are the spec: read each one fully). Use epic_sfx (already rebuilt in ${P} by the previous stage: read it) for braam / dhol / sitar / tabla / harmonium etc.
ACCEPTANCE: each of the four styles at 30 s meets section 5.3 (tempo within 0.2 BPM, phase within 15 ms with strength > 2, -16 +-0.2 LUFS, TP <= -3 dBTP); and each of the five ${P}/<slug>_music.py runs its render / verify entry point end to end with the rebuilt kit and meets its OWN documented targets (BPM grid, sections, drop-out at the reveal, loop seam, LUFS, TP). Write outputs to ${WF}/kitcheck/<slug>/ where the module allows an output dir, else let it write its normal workspace outputs. Look at the spectrograms. Commit + push epic_music.py. Return the numbers per style and per reel, and any contract item you could not satisfy.`

const sfxP = role('sound-designer', sfxTask, { label: 'kit:epic_sfx', phase: 'Kit', effort: 'max' })
const mixP = role('music-supervisor', mixTask, { label: 'kit:epic_mix', phase: 'Kit', effort: 'high' })
const sfxR = await sfxP
const musicR = await role('music-supervisor', musicTask, { label: 'kit:epic_music', phase: 'Kit', effort: 'max' })
const mixR = await mixP

phase('Verify')
const VSCHEMA = { type: 'object', properties: {
  verdict: { type: 'string', enum: ['OK', 'FIX'] },
  defects: { type: 'array', items: { type: 'object', properties: { module: { type: 'string', enum: ['epic_sfx', 'epic_music', 'epic_mix', 'fetch_sfx_library'] }, severity: { type: 'string', enum: ['blocker', 'major', 'minor'] }, what: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' } }, required: ['module', 'severity', 'what', 'fix'] } },
  reel_issues: { type: 'array', items: { type: 'object', properties: { slug: { type: 'string' }, what: { type: 'string' }, evidence: { type: 'string' } }, required: ['slug', 'what'] } },
  numbers: { type: 'string' } }, required: ['verdict', 'defects', 'reel_issues', 'numbers'] }
const verifyTask = (round) => `${KHEAD}
TASK (adversarial kit verifier, round ${round}; sound-designer + music-supervisor lens; DO NOT EDIT ANY FILE): the rebuilt kit ${P}/epic_sfx.py, epic_music.py, epic_mix.py (+ tools/fetch_sfx_library.py) must satisfy the CONTRACT. Try to BREAK it: (1) for every call site in kit_usage.txt and any more you find by grepping the reel modules, check the attribute exists and that the call as written runs (exercise it, with the callers' argument names and shapes); (2) for each of the five reels run the music render / verify entry point, the SFX register / cues / stem render, and the rough or final mix entry point (A and B) with the real VO from /home/user/100/workspace/jawad_reels/<slug>/vo/; record LUFS / TP / LRA / VO-over-bed against /home/user/100/brand_reels/design/LEAD_DECISIONS.md item 1; (3) listen by numbers: qc (clicks, DC, clipping), loop-seam discontinuity, spectrogram sanity (look at the PNGs). Write outputs only to ${WF}/kitcheck/verify_r${round}/ (or the module's normal workspace output if it has no output option). Report each defect with the owning kit module, severity, evidence and the fix; a problem inside a reel's own module that is not the kit's fault goes in reel_issues. 'numbers' = a compact per-reel table of what you measured.`
let verdict = await role('sound-designer', verifyTask(1), { label: 'kit:verify:r1', phase: 'Verify', schema: VSCHEMA, effort: 'high' })
let round = 1
while (verdict && verdict.verdict === 'FIX' && round <= 2) {
  const serious = (verdict.defects || []).filter(d => d.severity !== 'minor')
  if (!serious.length) break
  const byMod = {}
  for (const d of verdict.defects || []) { (byMod[d.module] = byMod[d.module] || []).push(d) }
  const mods = Object.keys(byMod).filter(m => byMod[m].some(d => d.severity !== 'minor'))
  await parallel(mods.map(m => () => role(m === 'epic_sfx' || m === 'fetch_sfx_library' ? 'sound-designer' : 'music-supervisor', `${KHEAD}
TASK: fix these verified defects in ${m === 'fetch_sfx_library' ? P + '/tools/fetch_sfx_library.py' : P + '/' + m + '.py'} (only that file${m === 'epic_sfx' ? ' and tools/fetch_sfx_library.py' : ''}). Defects: ${JSON.stringify(byMod[m]).slice(0, 9000)}. Re-run the exact failing checks, prove them fixed, and make sure nothing that passed before regressed (re-run your acceptance set). Commit + push the file(s). Return what you changed and the re-measured numbers.`, { label: `kit:fix:${m}:r${round}`, phase: 'Verify', effort: 'high' })))
  round++
  verdict = await role('sound-designer', verifyTask(round), { label: `kit:verify:r${round}`, phase: 'Verify', schema: VSCHEMA, effort: 'high' })
}
if (verdict && verdict.verdict === 'FIX') log(`kit: verify still reports ${(verdict.defects || []).length} defect(s) after ${round} round(s); releasing with them listed in KIT_READY`)

phase('Release')
const release = await agent(`Write the file ${WF}/KIT_READY as JSON {"released": true, "verify_rounds": ${round}, "verdict": ${JSON.stringify((verdict && verdict.verdict) || 'unknown')}, "open_defects": <the defects below>, "numbers": <the numbers string below>} and write ${WF}/kit_reel_issues.json with the reel_issues array below (exactly as given, pretty-printed). Then run: ${COMMIT} "Sound kit rebuilt and verified (epic_sfx, epic_music, epic_mix, sample fetcher)" ${P}/epic_sfx.py ${P}/epic_music.py ${P}/epic_mix.py ${P}/tools/fetch_sfx_library.py ${P}/sfx_library_LICENSES.md  (it prints 'nothing to commit' if the agents already committed everything; that is fine). Return the commit line.
DEFECTS: ${JSON.stringify((verdict && verdict.defects) || []).slice(0, 12000)}
NUMBERS: ${JSON.stringify((verdict && verdict.numbers) || '').slice(0, 6000)}
REEL_ISSUES: ${JSON.stringify((verdict && verdict.reel_issues) || []).slice(0, 12000)}`, { label: 'kit:release', phase: 'Release', effort: 'low' })
return { sfx: String(sfxR).slice(0, 2500), music: String(musicR).slice(0, 2500), mix: String(mixR).slice(0, 2500), verdict, release: String(release).slice(0, 500) }